# Thanks to http://blogs.perl.org/users/mauke/2017/10/automated-testing-on-windows-with-appveyor.html
# by mauke

cache:
  - C:\strawberry
    # This tree also includes the installed CPAN modules.

install:
  - if not exist C:\strawberry\ choco install strawberryperl -y
    # Need the trailing \ on c:\strawberry\ in order to test the existence
    # of the directory.*
  - set PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
  - cd %APPVEYOR_BUILD_FOLDER%
  - perl -v
  - cpanm --installdeps --notest --verbose .
  #- cpanm --installdeps --with-develop --notest .
    # shouldn't need develop dependencies to pass the tests, since those
    # dependencies aren't required on users' machines.

build_script:
  - perl Makefile.PL
  - gmake

test_script:
  #- echo Use just this line to succeed and save the cache.
  - gmake test

# * Thanks to https://stackoverflow.com/a/21041546/2877364
#   by https://stackoverflow.com/users/2964427/09stephenb and
#   https://stackoverflow.com/users/3814740/alexander-gelbukh for the tip.
